### ISSUE TITLE
Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by shinny-hongyan** [ActionsDesk/lfs-warning#107]
well I run this actions and get the error 
`Parameter token or opts.auth is required`
So, am I do some thing wrong?

**Comment by ppremk** [comment]
@shinny-hongyan do you have the screen capture or the output of the log file? Please do share your repo if its public.. I can help take a look.

**Comment by TomerFi** [comment]
@ppremk 

Happens to me on a private repo:

```text
Run actionsdesk/lfs-warning@v1.1
  with:
    filesizelimit: 5242880
/home/runner/work/_actions/actionsdesk/lfs-warning/v1.1/dist/index.js:7124
            throw new Error('Parameter token or opts.auth is required');
            ^

Error: Parameter token or opts.auth is required
    at Function.getAuthString (/home/runner/work/_actions/actionsdesk/lfs-warning/v1.1/dist/index.js:7124:19)
    at Function.getOctokitOptions (/home/runner/work/_actions/actionsdesk/lfs-warning/v1.1/dist/index.js:7089:29)
    at new GitHub (/home/runner/work/_actions/actionsdesk/lfs-warning/v1.1/dist/index.js:7073:22)
    at Object.104 (/home/runner/work/_actions/actionsdesk/lfs-warning/v1.1/dist/index.js:494:17)
    at __webpack_require__ (/home/runner/work/_actions/actionsdesk/lfs-warning/v1.1/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/actionsdesk/lfs-warning/v1.1/dist/index.js:37:19)
    at /home/runner/work/_actions/actionsdesk/lfs-warning/v1.1/dist/index.js:41:18
    at Object.<anonymous> (/home/runner/work/_actions/actionsdesk/lfs-warning/v1.1/dist/index.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

**Comment by TomerFi** [comment]
After tracing the error, I found [this](https://github.com/ActionsDesk/lfs-warning/blob/master/dist/index.js#L494) as the source.
I was able to work around this issue by adding the token as an environment variable.
I'm not sure I like this workaround.

```yaml
      - uses: actionsdesk/lfs-warning@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filesizelimit: '5242880'
```

**Comment by ppremk** [comment]
Hi @TomerFi 👋 

Thank you for catching this, I have blocked some time this Friday to dive into this. Keep you posted. 🙇

**Comment by TomerFi** [comment]
Thanks!

Great action, I really love using it.
Thank you!

**Comment by ppremk** [comment]
@TomerFi 

qq, are you using the action in a `private` repo?

**Comment by ppremk** [comment]
@TomerFi 
I've made some changes and have merged it in the `master` branch. There is some permission issue I'm waiting on to be able to publish the new release.

**Comment by TomerFi** [comment]
@ppremk 
Sorry for the delayed response, I was away.
Thank you very much, I'll check it out as soon as I can.
:-)

**Comment by TomerFi** [comment]
@ppremk 
I can confirm that [v2.0](https://github.com/ActionsDesk/lfs-warning/releases/tag/v2.0) fixed the issue for me.
I removed the "env" workaround, the following configuration now works well on my organization's private repo:

```yaml
- name: Warn for large files
  uses: actionsdesk/lfs-warning@v2.0
  with:
    filesizelimit: '5242880'
```

Thank you!

**Comment by ppremk** [comment]
> I can confirm that [v2.0](https://github.com/ActionsDesk/lfs-warning/releases/tag/v2.0) fixed the issue for me.
> I removed the "env" workaround, the following configuration now works well on my organization's private repo:

@TomerFi thank you for the confirmation. Im glad it worked out nicely.

Let's close this one out. ✅
