### ISSUE TITLE
Re-request admin rights for repo

### ISSUE THREAD

**Issue by ppremk** [ActionsDesk/lfs-warning#112]
@froi 👋 
As the maintainer of this repo, I would like to re-request the admin rights for this repo please 🙇 
Thank you in advance ❤️

**Comment by froi** [comment]
Hey friend. I could have sworn you had these rights already 🤔 .

In any case done!

**Comment by ppremk** [comment]
> Hey friend. I could have sworn you had these rights already 🤔 .

Thank you @froi ❤️
