### ISSUE TITLE
add additional check for files that should be in lfs (even if they are below size threshold)

### ISSUE THREAD

**Issue by naseemkullah** [ActionsDesk/lfs-warning#123]
e.g. If a user does not have lfs installed and  checks in a jpg which is below the threshold set by this action, this action will pass.

I would like to add an additional check to see if lfs tracked files are indeed being checked in as LFS files, even if they are below the size threshold set by the warning.

I think these two checks are complimentary, where the size one warns users that they should use LFS to store a file (even if its .js or .json, etc.) the check I will be adding will make sure that a file that is lfs tracked is not accidentally committed as a regular binary file.

**Comment by ppremk** [comment]
@naseemkullah thank you for this issue. I will be allocating some time to look into improvements as suggested. Please bare with me as I complete competing priorities before getting to this task. If you have some bandwidth, I am more than happy to review and approve a pull request ❤️ 🙇🏽

**Comment by naseemkullah** [comment]
Hello @ppremk I would be happy to! 😄 

Would you be alright if I converted to typescript?

I would compile the TS to JS in `/lib` and then from there use `ncc` to produce the final file like in: https://nils-braun.github.io/github-action/

**Comment by naseemkullah** [comment]
As for the implementation, I plan to iterate through the PR files and us `git check-attr` is used to determine if any of them should be stored in LFS.

Then among the PR files that should be stored in LFS (if any), check for the string `version https://git-lfs.github.com/spec/v1`  to determine if the file is indeed a pointer or not.

**Comment by naseemkullah** [comment]
@ppremk I added the functionality in the same PR that converts to TS, hope that is okay! (they are in separate commits), PTAL 🙏
