### ISSUE TITLE
Add contributors with write access

### ISSUE THREAD

**Issue by ppremk** [ActionsDesk/lfs-warning#132]
Hi @naseemkullah @TomerFi 

I've managed to get approval to add you folks as outside collaborators with write access to this repo. Once again, thank you for your contribution and patience in the process. Much appreciated 🙇🏽

**Comment by TomerFi** [comment]
Thanks for the acknowledgement.

**Comment by ppremk** [comment]
Closing this out since folks have accepted the invitation 🎉
